services:
  - type: web
    name: watchparty-server
    runtime: node
    plan: starter
    region: oregon
    buildCommand: pnpm install --recursive && turbo run build --filter=@watchparty/server...
    startCommand: cd apps/server && node dist/apps/server/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromGroup: web
